{
 "title": "Engula Overall",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(redis_up,namespace)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(redis_up{namespace=~\"$namespace\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Arena Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Usages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "redis_memory_used_rss_bytes{instance=\"$instance\"}",
     "legendFormat": "rss, {{instance}}"
    },
    {
     "expr": "redis_earena_block_size_bytes{instance=\"$instance\"}",
     "legendFormat": "blocks, {{instance}}"
    },
    {
     "expr": "redis_earena_record_size_bytes{instance=\"$instance\"}",
     "legendFormat": "records, {{instance}}"
    }
   ]
  },
  {
   "title": "Number of Blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "redis_earena_blocks{instance=\"$instance\"}",
     "legendFormat": "accumulated, {{instance}}"
    },
    {
     "expr": "redis_earena_indexed_blocks{instance=\"$instance\"}",
     "legendFormat": "realtime, {{instance}}"
    }
   ]
  },
  {
   "title": "Memory Block Writes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(redis_earena_block_size_bytes_total{instance=\"$instance\"}[1m])",
     "legendFormat": "new, {{instance}}"
    }
   ]
  },
  {
   "title": "Allocate/Free Records",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(redis_ea_alloc_records_total[1m])",
     "legendFormat": "allocate, {{instance}}"
    },
    {
     "expr": "rate(redis_ea_create_records_total[1m])",
     "legendFormat": "create, {{instance}}"
    },
    {
     "expr": "rate(redis_ea_free_records_total[1m])",
     "legendFormat": "free, {{instance}}"
    },
    {
     "expr": "rate(redis_ea_async_free_records_total[1m])",
     "legendFormat": "async_free, {{instance}}"
    },
    {
     "expr": "rate(redis_ea_blind_update_total[1m])",
     "legendFormat": "blind_update, {{instance}}"
    },
    {
     "expr": "rate(redis_ea_rmw_update_total[1m])",
     "legendFormat": "rmw_update, {{instance}}"
    }
   ]
  },
  { "title": "Arena Defragmentation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Memory Block Fill Ratio",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_defrag_fill_rate_bucket0_blocks{instance=\"$instance\"}",
     "legendFormat": "10%"
    },
    {
     "expr": "redis_defrag_fill_rate_bucket1_blocks{instance=\"$instance\"}",
     "legendFormat": "20%"
    },
    {
     "expr": "redis_defrag_fill_rate_bucket2_blocks{instance=\"$instance\"}",
     "legendFormat": "30%"
    },
    {
     "expr": "redis_defrag_fill_rate_bucket3_blocks{instance=\"$instance\"}",
     "legendFormat": "40%"
    },
    {
     "expr": "redis_defrag_fill_rate_bucket4_blocks{instance=\"$instance\"}",
     "legendFormat": "50%,"
    },
    {
     "expr": "redis_defrag_fill_rate_bucket5_blocks{instance=\"$instance\"}",
     "legendFormat": "60%"
    },
    {
     "expr": "redis_defrag_fill_rate_bucket6_blocks{instance=\"$instance\"}",
     "legendFormat": "70%"
    },
    {
     "expr": "redis_defrag_fill_rate_bucket7_blocks{instance=\"$instance\"}",
     "legendFormat": "80%"
    },
    {
     "expr": "redis_defrag_fill_rate_bucket8_blocks{instance=\"$instance\"}",
     "legendFormat": "90%"
    },
    {
     "expr": "redis_defrag_fill_rate_bucket9_blocks{instance=\"$instance\"}",
     "legendFormat": "100%"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "redis_earena_block_size_bytes/redis_earena_blocks{instance=\"$instance\"}",
     "legendFormat": "avg, {{instance}}"
    }
   ]
  },
  {
   "title": "Defragment Task Creations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(redis_defrag_task_create_requests_total{instance=\"$instance\"}[1m])",
     "legendFormat": "requests, {{instance}}"
    },
    {
     "expr": "rate(redis_defrag_task_create_succ_total{instance=\"$instance\"}[1m])",
     "legendFormat": "created"
    }
   ]
  },
  {
   "title": "Number of Blocks per Defragment Task",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(redis_defrag_completion_old_blocks_total{instance=\"$instance\"}[1m])/rate(redis_defrag_task_create_succ_total{instance=\"$instance\"}[1m])",
     "legendFormat": "before, {{instance}}"
    },
    {
     "expr": "rate(redis_defrag_completion_new_blocks_total{instance=\"$instance\"}[1m])/rate(redis_defrag_task_create_succ_total{instance=\"$instance\"}[1m])",
     "legendFormat": "after, {{instance}}"
    }
   ]
  },
  { "title": "Arena Compress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Compress Dictionary Normalized Size",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_ec_dict_nsize_bucket0_blocks{instance=\"$instance\"}",
     "legendFormat": "10%"
    },
    {
     "expr": "redis_ec_dict_nsize_bucket1_blocks{instance=\"$instance\"}",
     "legendFormat": "20%"
    },
    {
     "expr": "redis_ec_dict_nsize_bucket2_blocks{instance=\"$instance\"}",
     "legendFormat": "30%"
    },
    {
     "expr": "redis_ec_dict_nsize_bucket3_blocks{instance=\"$instance\"}",
     "legendFormat": "40%"
    },
    {
     "expr": "redis_ec_dict_nsize_bucket4_blocks{instance=\"$instance\"}",
     "legendFormat": "50%"
    },
    {
     "expr": "redis_ec_dict_nsize_bucket5_blocks{instance=\"$instance\"}",
     "legendFormat": "60%"
    },
    {
     "expr": "redis_ec_dict_nsize_bucket6_blocks{instance=\"$instance\"}",
     "legendFormat": "70%"
    },
    {
     "expr": "redis_ec_dict_nsize_bucket7_blocks{instance=\"$instance\"}",
     "legendFormat": "80%"
    },
    {
     "expr": "redis_ec_dict_nsize_bucket8_blocks{instance=\"$instance\"}",
     "legendFormat": "90%"
    },
    {
     "expr": "redis_ec_dict_nsize_bucket9_blocks{instance=\"$instance\"}",
     "legendFormat": "100%"
    }
   ]
  },
  {
   "title": "Compress Block Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(redis_ec_zip_completion_old_block_size_bytes_total{instance=\"$instance\"}[1m])",
     "legendFormat": "compress_old_bytes, {{instance}}"
    },
    {
     "expr": "rate(redis_ec_zip_completion_new_block_size_bytes_total{instance=\"$instance\"}[1m])",
     "legendFormat": "compress_new_bytes, {{instance}}"
    },
    {
     "expr": "rate(redis_ec_rezip_completion_old_block_size_bytes_total{instance=\"$instance\"}[1m])",
     "legendFormat": "recompress_old_bytes, {{instance}}"
    },
    {
     "expr": "rate(redis_ec_rezip_completion_new_block_size_bytes_total{instance=\"$instance\"}[1m])",
     "legendFormat": "recompress_new_bytes, {{instance}}"
    }
   ]
  },
  {
   "title": "Compress Dictionary",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "redis_ec_dicts{instance=\"$instance\"}",
     "legendFormat": "counts, {{instance}}"
    }
   ]
  },
  {
   "title": "Compress Blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "rate(redis_ec_zip_completion_old_blocks_total{instance=\"$instance\"}[1m])",
     "legendFormat": "compress_old_blocks, {{instance}}"
    },
    {
     "expr": "rate(redis_ec_zip_completion_new_blocks_total{instance=\"$instance\"}[1m])",
     "legendFormat": "compress_new_blocks, {{instance}}"
    },
    {
     "expr": "rate(redis_ec_rezip_completion_old_blocks_total{instance=\"$instance\"}[1m])",
     "legendFormat": "recompress_old_blocks, {{instance}}"
    },
    {
     "expr": "rate(redis_ec_rezip_completion_new_blocks_total{instance=\"$instance\"}[1m])",
     "legendFormat": "recompress_new_blocks, {{instance}}"
    }
   ]
  }
 ]
}