{
 "title": "Engula Compression",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(redis_up,namespace)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(redis_up{namespace=~\"$namespace\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Memory Blocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Fill Rate Bucket Blocks - Low",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "redis_defrag_fill_rate_bucket0_blocks{instance=\"$instance\"}",
     "legendFormat": "<30%,{{instance}}"
    },
    {
     "expr": "redis_defrag_fill_rate_bucket1_blocks{instance=\"$instance\"}",
     "legendFormat": "40%,{{instance}}"
    },
    {
     "expr": "redis_defrag_fill_rate_bucket2_blocks{instance=\"$instance\"}",
     "legendFormat": "50%,{{instance}}"
    },
    {
     "expr": "redis_defrag_fill_rate_bucket3_blocks{instance=\"$instance\"}",
     "legendFormat": "60%,{{instance}}"
    },
    {
     "expr": "redis_defrag_fill_rate_bucket4_blocks{instance=\"$instance\"}",
     "legendFormat": "70%,{{instance}}"
    },
    {
     "expr": "redis_defrag_fill_rate_bucket5_blocks{instance=\"$instance\"}",
     "legendFormat": "80%,{{instance}}"
    }
   ]
  },
  {
   "title": "Fill Rate Bucket Blocks - High",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "redis_defrag_fill_rate_bucket6_blocks{instance=\"$instance\"}",
     "legendFormat": "<85%,{{instance}}"
    },
    {
     "expr": "redis_defrag_fill_rate_bucket7_blocks{instance=\"$instance\"}",
     "legendFormat": "<90%,{{instance}}"
    },
    {
     "expr": "redis_defrag_fill_rate_bucket8_blocks{instance=\"$instance\"}",
     "legendFormat": "<95%,{{instance}}"
    },
    {
     "expr": "redis_defrag_fill_rate_bucket9_blocks{instance=\"$instance\"}",
     "legendFormat": "100%,{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Blocks - Others",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "redis_defrag_mutable_blocks{instance=\"$instance\"}",
     "legendFormat": "mutable, {{instance}}"
    },
    {
     "expr": "redis_defrag_immutable_recycling_blocks{instance=\"$instance\"}",
     "legendFormat": "recycling, {{instance}}"
    }
   ]
  },
  { "title": "Compress Lines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Number of Compress Lines - Low",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "redis_ec_lines_nsize_bucket0{instance=\"$instance\"}",
     "legendFormat": "10%,{{instance}}"
    },
    {
     "expr": "redis_ec_lines_nsize_bucket1{instance=\"$instance\"}",
     "legendFormat": "20%,{{instance}}"
    },
    {
     "expr": "redis_ec_lines_nsize_bucket2{instance=\"$instance\"}",
     "legendFormat": "30%,{{instance}}"
    },
    {
     "expr": "redis_ec_lines_nsize_bucket3{instance=\"$instance\"}",
     "legendFormat": "40%,{{instance}}"
    },
    {
     "expr": "redis_ec_lines_nsize_bucket4{instance=\"$instance\"}",
     "legendFormat": "50%,{{instance}}"
    }
   ]
  },
  {
   "title": "Number of Compress Lines - High",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "redis_ec_lines_nsize_bucket5{instance=\"$instance\"}",
     "legendFormat": "60%,{{instance}}"
    },
    {
     "expr": "redis_ec_lines_nsize_bucket6{instance=\"$instance\"}",
     "legendFormat": "70%,{{instance}}"
    },
    {
     "expr": "redis_ec_lines_nsize_bucket7{instance=\"$instance\"}",
     "legendFormat": "80%,{{instance}}"
    },
    {
     "expr": "redis_ec_lines_nsize_bucket8{instance=\"$instance\"}",
     "legendFormat": "90%,{{instance}}"
    },
    {
     "expr": "redis_ec_lines_nsize_bucket9{instance=\"$instance\"}",
     "legendFormat": "100%,{{instance}}"
    }
   ]
  },
  {
   "title": "Compress Lines - Others",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "redis_ec_lines_recycling{instance=\"$instance\"}",
     "legendFormat": "recycling, {{instance}}"
    },
    {
     "expr": "redis_ec_lines_skipped{instance=\"$instance\"}",
     "legendFormat": "skipped, {{instance}}"
    }
   ]
  },
  { "title": "Arena Compression", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Dictionary Number",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "redis_ec_dicts{instance=\"$instance\"}",
     "legendFormat": "total, {{instance}}"
    }
   ]
  },
  {
   "title": "Dict Costs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "redis_ec_dicts_cost_size_bytes{instance=\"$instance\"} / redis_ec_dicts{instance=\"$instance\"}",
     "legendFormat": "costs/dict, {{instance}}"
    }
   ]
  },
  {
   "title": "Dict Async Deleted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "redis_ec_dicts_async_deleted_total{instance=\"$instance\"}",
     "legendFormat": "number, {{instance}}"
    }
   ]
  },
  {
   "title": "Dict Async Deleting",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "redis_ec_dicts_async_deleting{instance=\"$instance\"}",
     "legendFormat": "number, {{instance}}"
    }
   ]
  }
 ]
}