{
 "title": "Engula Schedule",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(redis_up,namespace)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(redis_up{namespace=\"$namespace\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Busy Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "redis_coro_main_thread_busy_level{instance=\"$instance\"}",
     "legendFormat": "Level, {{instance}}"
    }
   ]
  },
  {
   "title": "Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "redis_ea_que_zip_reqs_queue_size{instance=\"$instance\"}",
     "legendFormat": "zip, {{instance}}"
    },
    {
     "expr": "redis_ea_que_rezip_reqs_queue_size{instance=\"$instance\"}",
     "legendFormat": "rezip, {{instance}}"
    },
    {
     "expr": "redis_ea_que_defrag_reqs_queue_size{instance=\"$instance\"}",
     "legendFormat": "defrag, {{instance}}"
    },
    {
     "expr": "redis_ea_que_completion_queue_size{instance=\"$instance\"}",
     "legendFormat": "completion, {{instance}}"
    }
   ]
  },
  {
   "title": "Main Thread Busy Level Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "increase(redis_coro_main_thread_busy_level_useconds_total0{instance=\"$instance\"}[1m])",
     "legendFormat": "L0, {{instance}}"
    },
    {
     "expr": "increase(redis_coro_main_thread_busy_level_useconds_total1{instance=\"$instance\"}[1m])",
     "legendFormat": "L1, {{instance}}"
    },
    {
     "expr": "increase(redis_coro_main_thread_busy_level_useconds_total2{instance=\"$instance\"}[1m])",
     "legendFormat": "L2, {{instance}}"
    },
    {
     "expr": "increase(redis_coro_main_thread_busy_level_useconds_total3{instance=\"$instance\"}[1m])",
     "legendFormat": "L3, {{instance}}"
    },
    {
     "expr": "increase(redis_coro_main_thread_busy_level_useconds_total4{instance=\"$instance\"}[1m])",
     "legendFormat": "L4, {{instance}}"
    }
   ]
  },
  {
   "title": "Schedule Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "increase(redis_coro_schedule_soft_limit_useconds_total{instance=\"$instance\"}[1m])/increase(redis_coro_schedule_total{instance=\"$instance\"}[1m])",
     "legendFormat": "soft_limit, {{instance}}"
    },
    {
     "expr": "increase(redis_coro_schedule_hard_limit_useconds_total{instance=\"$instance\"}[1m])/increase(redis_coro_schedule_total{instance=\"$instance\"}[1m])",
     "legendFormat": "hard_limit, {{instance}}"
    },
    {
     "expr": "increase(redis_coro_schedule_plan_useconds_total{instance=\"$instance\"}[1m])/increase(redis_coro_schedule_total{instance=\"$instance\"}[1m])",
     "legendFormat": "plan, {{instance}}"
    },
    {
     "expr": "increase(redis_coro_schedule_real_useconds_total{instance=\"$instance\"}[1m])/increase(redis_coro_schedule_total{instance=\"$instance\"}[1m])",
     "legendFormat": "real, {{instance}}"
    }
   ]
  },
  { "title": "Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Defrag Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "increase(redis_ea_que_defrag_reqs_by_main_thread_total{instance=\"$instance\"}[1m])",
     "legendFormat": "main_thread, {{instance}}"
    },
    {
     "expr": "increase(redis_ea_que_defrag_reqs_send_total{instance=\"$instance\"}[1m]) - increase(redis_ea_que_defrag_reqs_by_main_thread_total{instance=\"$instance\"}[1m])",
     "legendFormat": "io_threads, {{instance}}"
    },
    {
     "expr": "increase(redis_ea_que_defrag_reqs_urgent_total{instance=\"$instance\"}[1m])",
     "legendFormat": "urgent, {{instance}}"
    }
   ]
  },
  {
   "title": "ZIP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "increase(redis_ea_que_zip_reqs_by_main_thread_total{instance=\"$instance\"}[1m])",
     "legendFormat": "by_main, {{instance}}"
    },
    {
     "expr": "increase(redis_ea_que_zip_reqs_send_total{instance=\"$instance\"}[1m]) - increase(redis_ea_que_zip_reqs_by_main_thread_total{instance=\"$instance\"}[1m])",
     "legendFormat": "io_threads,{{instance}}"
    },
    {
     "expr": "increase(redis_ea_que_zip_reqs_urgent_total{instance=\"$instance\"}[1m])",
     "legendFormat": "urgent, {{instance}}"
    }
   ]
  },
  {
   "title": "ReZIP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "increase(redis_ea_que_rezip_reqs_by_main_thread_total{instance=\"$instance\"}[1m])",
     "legendFormat": "main_thread, {{instance}}"
    },
    {
     "expr": "increase(redis_ea_que_rezip_reqs_send_total{instance=\"$instance\"}[1m]) - increase(redis_ea_que_rezip_reqs_by_main_thread_total{instance=\"$instance\"}[1m])",
     "legendFormat": "io_threads, {{instance}}"
    }
   ]
  }
 ]
}