{
 "title": "Engula Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(redis_up,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Memory Block / Dict Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Block Number",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "redis_earena_indexed_blocks{instance=\"$instance\"}",
     "legendFormat": "art block number"
    }
   ]
  },
  {
   "title": "Dict Number",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "redis_ec_dicts{instance=\"$instance\"}",
     "legendFormat": "dict number"
    }
   ]
  },
  {
   "title": "Block Eff Record Size Percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "(redis_earena_record_size_bytes{instance=\"$instance\"} * 100) / redis_earena_block_size_bytes{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Compressed Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(redis_ec_zip_completion_old_block_size_bytes_total{instance=\"$instance\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(redis_ec_zip_completion_new_block_size_bytes_total{instance=\"$instance\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Allocator / Task Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "EAllocator Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(redis_ea_alloc_records_total{instance=\"$instance\"}[1m])",
     "legendFormat": "ea_alloc_records_total"
    },
    {
     "expr": "rate(redis_ea_create_records_total{instance=\"$instance\"}[1m])",
     "legendFormat": "ea_create_records_total"
    },
    {
     "expr": "rate(redis_ea_free_records_total{instance=\"$instance\"}[1m])",
     "legendFormat": "ea_free_tot_count"
    }
   ]
  },
  {
   "title": "Defrag Task Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(redis_ea_que_defrag_req_sends_total{instance=\"$instance\"}[1m])",
     "legendFormat": "ea_que_defrag_req_sends_total"
    },
    {
     "expr": "rate(redis_ea_que_defrag_completions_total{instance=\"$instance\"}[1m])",
     "legendFormat": "ea_que_defrag_completions_total"
    }
   ]
  },
  {
   "title": "Defrag Block Number Change",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "rate(redis_defrag_completion_old_blocks_total{instance=\"$instance\"}[1m])",
     "legendFormat": "defrag_completion_old_blocks_total"
    },
    {
     "expr": "rate(redis_defrag_completion_new_blocks_total{instance=\"$instance\"}[1m])",
     "legendFormat": "defrag_completion_new_blocks_total"
    }
   ]
  },
  {
   "title": "Zip Task Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "rate(redis_ea_que_zip_req_sents_total{instance=\"$instance\"}[1m])",
     "legendFormat": "ea_que_zip_req_sents_total"
    },
    {
     "expr": "rate(redis_ea_que_zip_req_main_thread_total{instance=\"$instance\"}[1m])",
     "legendFormat": "ea_que_zip_req_main_thread_total"
    },
    {
     "expr": "rate(redis_ea_que_zip_completions_total{instance=\"$instance\"}[1m])",
     "legendFormat": "ea_que_zip_completions_total"
    }
   ]
  },
  {
   "title": "Zip Block Number Change",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "rate(redis_ec_zip_completion_old_blocks_total{instance=\"$instance\"}[1m])",
     "legendFormat": "ec_zip_completion_old_blocks_total"
    },
    {
     "expr": "rate(redis_ec_zip_completion_new_blocks_total{instance=\"$instance\"}[1m])",
     "legendFormat": "ec_zip_completion_new_blocks_total"
    }
   ]
  },
  {
   "title": "Re-Zip Task Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "rate(redis_ea_que_rezip_req_sents_total{instance=\"$instance\"}[1m])",
     "legendFormat": "ea_que_rezip_req_sents_total"
    },
    {
     "expr": "rate(redis_ea_que_rezip_completions_total{instance=\"$instance\"}[1m])",
     "legendFormat": "ea_que_rezip_completions_total"
    }
   ]
  },
  {
   "title": "ReZip Block Number Change",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "rate(redis_ec_rezip_completion_old_blocks_total{instance=\"$instance\"}[1m])",
     "legendFormat": "ec_rezip_completion_old_blocks_total"
    },
    {
     "expr": "rate(redis_ec_rezip_completion_new_blocks_total{instance=\"$instance\"}[1m])",
     "legendFormat": "ec_rezip_completion_new_blocks_total"
    }
   ]
  }
 ]
}