{
 "title": "Engula Defragmentation",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(redis_up,namespace)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(redis_up,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "redis_memory_used_bytes{instance=\"$instance\"}",
       "legendFormat": "zmalloc,{{instance}}"
      },
      {
       "expr": "(redis_memory_used_bytes{instance=\"$instance\"} - redis_mem_not_counted_for_eviction_bytes{instance=\"$instance\"})",
       "legendFormat": "logic,{{instance}}"
      },
      {
       "expr": "redis_engula_arena_mutable_zone_bytes{instance=\"$instance\"}",
       "legendFormat": "mutable_blocks,{{instance}}"
      }
     ]
    },
    {
     "title": "Memory Blocks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "redis_engula_recyclable_bytes{instance=\"$instance\"}",
       "legendFormat": "recyclable,{{instance}}"
      }
     ]
    },
    {
     "title": "Overhead",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "redis_mem_not_counted_for_eviction_bytes{instance=\"$instance\"}",
       "legendFormat": "overhead,{{instance}}"
      }
     ]
    },
    {
     "title": "Memory To Free",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "clamp_min(redis_memory_used_bytes{instance=\"$instance\"} - redis_mem_not_counted_for_eviction_bytes{instance=\"$instance\"} - redis_memory_max_bytes{instance=\"$instance\"}, 0)",
       "legendFormat": "tofree,{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Defragmentation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Defragmentation Trigger",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(redis_engula_evict_urgent_defrag_timer_total{instance=\"$instance\"}[1m])",
     "legendFormat": "evict_timer,{{instance}}"
    },
    {
     "expr": "rate(redis_engula_evict_urgent_defrag_wall_total{instance=\"$instance\"}[1m])",
     "legendFormat": "evict_func,{{instance}}"
    }
   ]
  },
  {
   "title": "Defragmentation Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(redis_engula_ea_que_defrag_reqs_send_total{instance=\"$instance\"}[1m])",
     "legendFormat": "send_que,{{instance}}"
    },
    {
     "expr": "rate(redis_engula_defrag_inline_urgent_total{instance=\"$instance\"}[1m])",
     "legendFormat": "urgent,{{instance}}"
    }
   ]
  },
  {
   "title": "Evict Timer Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "redis_engula_evict_timer_active{instance=\"$instance\"}",
     "legendFormat": "evict_timer_status,{{instance}}"
    }
   ]
  },
  {
   "title": "Evict Timer Start",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(redis_engula_evict_timer_starts_total{instance=\"$instance\"}[1m])",
     "legendFormat": "start_total,{{instance}}"
    }
   ]
  }
 ]
}